### ISSUE TITLE
大佬，FT中文网的脚本是针对带锁的文章的么？

### ISSUE THREAD

**Issue by StephenAnboer** [ttttmr/UserJS#2]
貌似还是不能加载全文呀

**Comment by ttttmr** [comment]
没有提供“破解”，真的只是自动点击“加载全文”的按钮，该付费还是要付费😂，最近更新是用于`http://www.ftchinese.com/`自动跳转`https://www.chineseft.com/`

**Comment by ttttmr** [comment]
ps: 你头像好像是我壁纸哈哈哈

**Comment by StephenAnboer** [comment]
哈哈，这个就是那张著名的壁纸
